kind: Service                           # Defines to create Service type Object
apiVersion: v1
metadata:
  name: vprodb                          # should be same as provided in the properties file
spec:
  ports:
    - port: 3306                        # Containers port exposed
      targetPort: vprodb-port           # Pods port, can be accessed from the defined port name in deploy definition
      protocol: TCP
  selector:
    app: vprodb                         # Apply this service to any pods which has the specific label
  type: ClusterIP