kind: Service                             # Defines to create Service type Object
apiVersion: v1
metadata:
  name: vprocache01     # should be same as provided in the properties file
spec:
  ports:
    - port: 11211                               # Containers port exposed
      targetPort: vpromc-port                   # Pods port, as defined port name in deploy definition
      protocol: TCP
  selector:
    app: vpromc                    # Apply this service to any pods which has the specific label
  type: ClusterIP