kind: Service                      # Defines to create Service type Object
apiVersion: v1
metadata:
  name: vproapp-service            # should be same as provided in the properties file
spec:
  ports:
    - port: 80                      # loadbalancer port / nginx endpoint port
      targetPort: vproapp-port      # Pods port, as defined port name from deploy definition
      protocol: TCP
  selector:
    app: vproapp                    # Apply this service to any pods which has the specific label
  type: LoadBalancer